-- --------------------------------------------------------------
-- fill_quizz.sql
-- Used to fill 'question' table
-- Use the following form for your insert clauses:
-- INSERT INTO question (q_quest, q_lvl, q_ans_a, q_ans_b, q_ans_c, q_ans_d, q_right_ans) VALUES 
-- ('<question>', <level id>, '<answer a>', '<answer b>', '<answer c>', '<answer d>', '<list of right answers>');
-- IMPORTANT:
--  - Do not forget to escape simple quotes in strings ;
--  - for the right answers, list letters without spaces (example: 'ab', or 'acd')
--  - Each time I'll execute the script, I'll comment insert clauses runed
-- Levels:
-- 1 = LPI-101
-- 2 = LPI-102
-- 3 = LPI-201
-- 4 = LPI-202
-- 5 = LPI-301
-- 6 = LPI-302
-- 7 = LPI-303
-- And very important : sorry for my bad english :o)
-- --------------------------------------------------------------

--INSERT INTO question (q_quest, q_lvl, q_ans_a, q_ans_b, q_ans_c, q_ans_d, q_right_ans) VALUES 
--("Comment est représenté le périphérique IDE esclave du deuxième contrôleur ?", 1, "hda", "sdc", "hdc1", "hdd", "d");
